### ISSUE TITLE
[Startup] Linux instruction

### ISSUE THREAD

**Issue by KaiL4eK** [KaiL4eK/STM32_ChibiOS#17]
Просьба провести ревизию и протестировать

**Comment by serykhelena** [comment]
export PATH="$PATH:$HOME/ChibiStudio"
ChibiStudio

Нужно ли ChibiStudio? Так получается, что при запуске терминала у меня сразу открывается Eclipse...

**Comment by KaiL4eK** [comment]
Там же написано, прописать строку установки переменной..)

**Comment by serykhelena** [comment]
Витиевато излагаешь, сударь >______<
