### ISSUE TITLE
[Linux_setup.md] Уточнить

### ISSUE THREAD

**Issue by RuslanZhuch** [KaiL4eK/STM32_ChibiOS#18]
> export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/local_libs/lib"
> Можете закинуть в конец ~/.bashrc эту строку, чтобы она устанавливалась при каждом создании терминала

Возможно, стоит уточнить, что под ~/.bashrc понимается файл, в конец которого необходимо прописать глобальные пути (или привести примеры)

**Comment by KaiL4eK** [comment]
Спасибо! Перефразировал
