### ISSUE TITLE
Посмотреть HAL_topics/UART_setup.md

### ISSUE THREAD

**Issue by serykhelena** [KaiL4eK/STM32_ChibiOS#2]
@KaiL4eK  добавь, пожалуйста, про выбор скорости передачи данных. Почему мы выбираем такие значения и чуть подробнее про .cr2 в конфигурации UART 😃

**Comment by KaiL4eK** [comment]
фикс сделан, инфы для начала работы достаточно на мой взгляд
@serykhelena  если ок - закрывай

**Comment by serykhelena** [comment]
Ок ^____________^
