### ISSUE TITLE
[HAL_setup/PWM_ICU] Пин для PWM3/3

### ISSUE THREAD

**Issue by RuslanZhuch** [KaiL4eK/STM32_ChibiOS#21]
В [main.c](https://github.com/KaiL4eK/STM32_ChibiOS/blob/master/HAL_setup/PWM_ICU/main.c):
`/* Setup PWM pin */
    palSetPadMode( GPIOB, 0, PAL_MODE_ALTERNATE(2) );	// PB_0 - PWM3/3, set for timer function`

Для этого канала используется пин PC_8
PB_0 - LED1

**Comment by KaiL4eK** [comment]
![image](https://user-images.githubusercontent.com/13577066/53050593-c2df2780-34aa-11e9-9647-528f34aa3fec.png)
![image](https://user-images.githubusercontent.com/13577066/53050621-cf638000-34aa-11e9-8f58-b5411f2915b2.png)
На то они и альтернативные, в этом примере как раз предлагается яркостью диода и поуправлять.
