### ISSUE TITLE
[Linux_setup] Уточнить

### ISSUE THREAD

**Issue by serykhelena** [KaiL4eK/STM32_ChibiOS#22]
Не получается запустить скрипт load.sh из терминала. 
Нагуглила, что нужно прописать ./load.sh - говорит, что нет разрешения.
Можешь, пожалуйста, поподробнее написать, что нужно сделать.
Правильно я понимаю, что, например, если я хочу писать код просто в текстовом редакторе (например, Sublime Text), то из терминала я могу собирать проект и загружать?

**Comment by KaiL4eK** [comment]
Добавил инфо, есть подозрение, что со скрипта слетаю права, если репозиторий закоммитить из винды. В этом плане инфа должна быть универсальна, так как решать такую проблему на лялихе (Linux) приходится часто.

**Comment by KaiL4eK** [comment]
А и ответ на вопрос, да, можешь, конечно) В инструкции это даже где-то есть.
