### ISSUE TITLE
[Linux_setup] Вопрос про отладчик

### ISSUE THREAD

**Issue by serykhelena** [KaiL4eK/STM32_ChibiOS#23]
Важно ли в какую папку клонируешь репозиторий `openocd`?

**Comment by KaiL4eK** [comment]
Сама по себе концепция сборки предполагает, что исходники могут валяться где угодно. Важно укахать точный путь инсталяции. Для целей укомплектования всех собираемых либ в инструкции создается папку `ext_repos`, чтобы не мусорить в домашней папке и при желании посе инсталяции снести одним жестом.

**Comment by KaiL4eK** [comment]
Нужно добавить инфу о том, куда клонировать?

**Comment by serykhelena** [comment]
Мне кажется, лучше добавить (=

**Comment by serykhelena** [comment]
Спасибо! 
А скажи, что ты имел в виду "Переходим в папку cd openocd и делаем сборку по readme:"? 
Нужно открыть readme и сделать Quick Start или всё же использовать команды, которые ты ниже приводишь? Мне не очень понятно )=

**Comment by KaiL4eK** [comment]
Видать лишнего написал, думаешь стоит убрать? В README просто описано, как собирать, шаги абсолютно идентичные)

**Comment by serykhelena** [comment]
Может так и написать, что в README можно посмотреть более подробно, что и как собирать, но команды ты уже и так приводишь? (=
