### ISSUE TITLE
[Linux_setup] Java ругается при запуске Eclipse 

### ISSUE THREAD

**Issue by serykhelena** [KaiL4eK/STM32_ChibiOS#24]
Может быть добавить?
У меня при попытке запуска Eclipse, вылезает ошибка

**Comment by KaiL4eK** [comment]
Добавил инфо об установке jdk и jre, посмотри, пожалуйста, поможет ли это, если решает проблему - закрывай)

**Comment by serykhelena** [comment]
Помогло (=
