### ISSUE TITLE
[Linux_setup] PATH и Eclipse

### ISSUE THREAD

**Issue by serykhelena** [KaiL4eK/STM32_ChibiOS#25]
Может быть немного уточнить инфу про то, что нужно прописать переменную PATH.
Это достаточно сделать в терминале или нужно также добавить в .bashrc ?

**Comment by KaiL4eK** [comment]
Хорошее уточнение, сами переменные предполагают установку на нынешний терминал (сессию), но если вкатить в *rc файл и вспомнить, что этот *rc файл запускается при каждом создании, то получаем установку на все терминалы.
Инфу добавил, достаточно ли этого или нужно еще конкретизировать?

**Comment by serykhelena** [comment]
Добавила в .bashrc, но не помогло. 
В терминале пробовала вводить просто ChibiStudio и ./ChibiStudio, автодополнение не работает, пишет команда не найдена. Я что-то не так делаю?

**Comment by KaiL4eK** [comment]
Где лежит папка ChibiStudio?

**Comment by serykhelena** [comment]
в Downloads

**Comment by KaiL4eK** [comment]
А PATH, полагаю, прописан до `$HOME/ChibiStudio`?

**Comment by serykhelena** [comment]
Да, до меня теперь тоже дошло... 
Сейчас поменяю (=

**Comment by KaiL4eK** [comment]
Я бы указал на это в инструкции, но пускай это будем маленькой заковыркой, чтобы размяться =)

**Comment by KaiL4eK** [comment]
А то мы тут о cmake, configure, сборке пакетов говорим, так вот пусть будет маленький сюрпрайз)

**Comment by serykhelena** [comment]
Хо-хо-хо! (=
Теперь всё работает (= Закрываю issue

**Comment by KaiL4eK** [comment]
В инструкции пишутся фразы "Перейдя в папку" и "указав переменную PATH до этой папки", так что пускай разбираются)
