### ISSUE TITLE
[hal_topics/setup -> EXT] Уточнить про структуру конфигурации 

### ISSUE THREAD

**Issue by KaiL4eK** [KaiL4eK/STM32_ChibiOS#26]
Долгими мучениями дошли до того, что при вызове `extStart()` конфигурационная структура должна быть статической или глобальной. Драйвер сохраняет указатель на структуру вместо самой структуры. Работа с локальной структурой (выделена на стеке) может привести к тому, что память, на которую ссылается сохраненный адрес, будет переписана и дальше `undefined behaviour`.

**Comment by RuslanZhuch** [comment]
Аналогичная ситуация с icu
Моментально выбрасывает в цикл для необработанных исключений при вызове коллбэков

**Comment by KaiL4eK** [comment]
Так как на новой версии модуль удален - вопрос исчерпан. Проблемы с локальным выделением структуры считаю стоит решать локально. Тем не менее бага будет в истории - будем знать)
