### ISSUE TITLE
[hal_topics/uart] Название топика

### ISSUE THREAD

**Issue by KaiL4eK** [KaiL4eK/STM32_ChibiOS#3]
Смущает тот факт, что мы не учитываем разделение в ChibiOS драйверов UART и Serial, что может ввести в замешательство. Полагаю, стоит в начале топика обратить внимание на то, что Serial является оберткой над UART, что в свою очередь предоставляет удобный функционал по сравнению с необходимостью работать с прерываниями.
Из того, что надо сделать - думаю стоит переименовать топик в Serial и все упоминания UART также перевести на Serial Driver.

**Comment by serykhelena** [comment]
Done 😎
