### ISSUE TITLE
[HAL/ADC] Опечатка

### ISSUE THREAD

**Issue by Shnuer** [KaiL4eK/STM32_ChibiOS#31]
`sqr2` - регистр настройки последовательности снятия аналогового сигнала и записи в буффер, возможные значения:

ADC_SQR2_SQ[7-12]_N() - макрос задания каналов для порядковых номеров 7-12, возможные значения макроса аналогичные

 `sqr2` - регистр настройки последовательности снятия аналогового сигнала и записи в буффер, возможные значения:

**Comment by KaiL4eK** [comment]
В чем очепятка?

**Comment by Shnuer** [comment]
В описании идет sqr1, sqr2, sqr3 в тексте небольшая опечатка sqr1, sqr2, sqr2. Т.е. sqr2 вместо sqr3.
