### ISSUE TITLE
Инструкция по добавлению файлов

### ISSUE THREAD

**Issue by serykhelena** [KaiL4eK/STM32_ChibiOS#34]
Было бы хорошо сделать инструкцию про то, как редактировать файл project.mk, чтобы можно было создавать свои файлы и компилятор не ругался бы

**Comment by KaiL4eK** [comment]
В коммите 5155e93658b457afa3fb64eba7f6af077080f4ff переработал инструкции, достаточно ли данной информации для работы с project.mk?

**Comment by KaiL4eK** [comment]
https://github.com/KaiL4eK/STM32_ChibiOS/commit/eb9f0e8029a7699dd304bc066554aae74c857027
