### ISSUE TITLE
[HAL_topics/EXT_setup.md] Исправить инфу о каналах модуля EXT

### ISSUE THREAD

**Issue by serykhelena** [KaiL4eK/STM32_ChibiOS#7]
В даташите я нашла, что у EXT 16 каналов (начиная с 0-го), но при конфигурации этого модуля - там получается больше строк. Возможно, я заблуждаюсь в процессе выбора пина для генерации внешнего прерывания. Можешь посмотреть, пожалуйста (=

**Comment by KaiL4eK** [comment]
Немножко обнаглею, но можно ссылку на страницу?) В метро еду)

**Comment by serykhelena** [comment]
Прошу (= https://github.com/KaiL4eK/STM32_ChibiOS/blob/master/HAL_topics/EXT_setup.md

**Comment by KaiL4eK** [comment]
В DS плз :neutral_face:

**Comment by KaiL4eK** [comment]
Про 16 каналов

**Comment by serykhelena** [comment]
https://www.st.com/content/ccc/resource/technical/document/datasheet/group3/c5/37/9c/1d/a6/09/4e/1a/DM00273119/files/DM00273119.pdf/jcr:content/translations/en.DM00273119.pdf#page=26 

На всякий случай, стр. 26

**Comment by KaiL4eK** [comment]
Дело верное указано, смущает наличие 25 компараторов, но, думаю, правильно отмечено, что ног у портов обычно 16, так что не паримся и работаем только с 16ю элементами
Я ещё капну в исходники, но для действий по умолчанию лучше пользовать 16 элементов 🤔

**Comment by KaiL4eK** [comment]
В исходниках вообще переменная EXT_MAX_CHANNELS установлена в 20..
Тему закрываю, используем 16 каналов
